language: cpp
compiler: gcc
dist: bionic
os: linux
python:
  - 3.7
  - 3.8
notifications:
  on_success: change
  on_failure: always

before_install:
  # C++14 & Codecov
  - sudo pip install codecov
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  # C++14 & Codecov
  - sudo apt-get install -qq g++-5
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 90

script: 
  - g++ main.cpp -std=c++14 -o main -O2
  - ./main
  - codecov

addons:
    apt:
        packages: libboost-all-dev

after_success: 
    # Codecov
    - bash <(curl -s https://codecov.io/bash)